### ISSUE TITLE
Support to Mojave

### ISSUE THREAD

**Issue by kauefontes** [edu-rinaldi/hackintosh-z370p-i5-8400-gtx-1060#1]
Hey bro! How are you? I'm Kauê, From Brazil.
Do you have tried this settings to mojave? I'm buying exactly this setup(excep for the gCard, i'll use a rx580/480) and i'm really interested in this!

Thanks for the amazing hack!

**Comment by fabianclain** [comment]
I'm also interested in support for Mojave. I'm building the exact same build with RX 580 GPU.
@kauefontes have you managed to get it up and running? have you experienced any problems? are you using the m2 port?

**Comment by kauefontes** [comment]
Hi @sdet-ro , I've changed my setup to something more affordable so my MoBo is a Gigabyte H310 D3, with a I3-8100. Also using a Sapphire Nitro+ RX580 4GB(arriving to me in the next week). As soon i have my MacOs installed, I'll upload to a repository. Hope it helps you, once the coffee lake iGPU is the same for the i3, i5 and i7. If you haven't buy your discrete GPU, i recommend take one from Sapphire, according to various Hackintosh forums this GPU works OOB.

**Comment by fabianclain** [comment]
I'll be using the same GPU, it already arrived for me. However, I've ordered the z370-p mobo, I will need kexts for that one.

**Comment by kauefontes** [comment]
Depending your sound/network chipset, i think we can share the same kexts. Only changes is when we generate the specific DSDT/SSDT files, that is different to every MoBo.

**Comment by fabianclain** [comment]
I will get back to you next week, after I get my mobo..

**Comment by kauefontes** [comment]
Sure... You can also take a look on the website of the MoBo(i recommend that you get a Gigabyte model). You can have all the information there.

**Comment by kauefontes** [comment]
@sdet-ro I uploaded my EFI today, I made a vanilla installation and it is working like a charm! If you want to, you can take a look into my EFI.

**Comment by fabianclain** [comment]
@kauefontes thank you so much. I have managed to create a vanilla installation for Asus Prime Z370P.
Everything works, all it's needed is just to replace the EFI folder.
You can see/get the working EFI here: https://github.com/sdet-ro/Hackintosh-Asus-PrimeZ370-P

**Comment by kauefontes** [comment]
nice bro! thank you for the feedback!
I'll close this issue for now, I think both of us are done with it! Hope our refi helps many people! hehe
